[package]
name = "x"
version = "0.1.0"
edition = "2024"
description = "Run any source file with one command"
repository = "https://github.com/Md-Talim/x"
readme = "README.md"
keywords = ["cli", "runner", "compiler", "developer-tools", "x", "execute"]
